Installation page: use 'main' branch, add direct artifact links
duckdb/duckdb-web pull request #1030
Opened 2023-08-23 16:23 UTC by szarnyasg

The MacOS build currently fails so those links fail because there is no older build for `main` to fall back to (only `master`): https://github.com/duckdb/duckdb/actions?query=branch:main+event:repository_dispatch+workflow:OSX

2023-08-24 12:02 UTC, szarnyasg commented
So the links work with `wget` but not with `curl`.
See https://stackoverflow.com/questions/20986395/why-does-curl-not-work-but-wget-works
This can be fixed by using `curl -L`. I added example commands to the boxes in the Installation page. Browsers can follow the links just fine.

2023-08-24 12:03 UTC, szarnyasg commented
This should only be merged once the OS X build is fixed, which is expected happen after https://github.com/duckdb/duckdb/pull/8674

2023-08-24 14:44 UTC, carlopi commented
It would be nice to eventually have a complete script, like:

```
wget artifacts.duckdb.org/linux.zip
unzip linux.zip
unzip linux_cli.zip
chmod +x duckdb
./duckdb --version
```

2023-08-24 14:52 UTC, szarnyasg commented
My biggest discovery today is that you can save one line using `jar` to unzip:
```sh
curl -L https://artifacts.duckdb.org/latest/duckdb-binaries-linux.zip | jar x
jar xf duckdb_cli-linux-amd64.zip
chmod +x duckdb
./duckdb
```

2023-08-24 15:12 UTC, carlopi commented
At the cost of an extra dependency / black magic feel.

2023-08-24 15:16 UTC, szarnyasg commented
Sure - it's not something I'd put on the Installation page :).

2023-08-25 04:51 UTC, Mause requested changes
You'll need to update the scripts that correspond to this functionality as well

2023-08-25 07:24 UTC, szarnyasg commented
Good point, I updated the JS.

2023-08-25 11:13 UTC, szarnyasg commented
This PR fixes #1030 using artifacts.duckdb.org

2023-08-25 11:58 UTC, Mause commented
> This PR fixes #1030 using artifacts.duckdb.org

Er, 1030 is this pr?

2023-08-25 12:18 UTC, szarnyasg commented
Oh no, we have fallen into a recursion loop :)

2023-08-25 12:19 UTC, szarnyasg commented
This PR fixes #281 using artifacts.duckdb.org

2023-08-25 12:57 UTC, Mause requested changes
I'm not sure how important providing commands is? I think it's more important to have clickable links

Either way, some minor corrections

2023-08-25 12:57 UTC, Mause commented on _includes/installation.html
> +		Java main builds are available in the sonatype snapshots repository, which can be accessed with the following:
```suggestion
		Java dev builds are available in the sonatype snapshots repository, which can be accessed with the following:
```

2023-08-25 12:57 UTC, Mause commented on _includes/installation.html
> +		curl -L https://artifacts.duckdb.org/latest/duckdb-binaries-osx.zip -o duckdb-binaries-osx.zip
```suggestion
		curl -L https://artifacts.duckdb.org/latest/duckdb-binaries-osx.zip -O
```

2023-08-25 12:57 UTC, Mause commented on _includes/installation.html
> +		curl -L https://artifacts.duckdb.org/latest/duckdb-binaries-windows.zip -o duckdb-binaries-windows.zip
Curl isn't really used on Windows, except as the alias inside powershell (maybe just use invoke web request directly instead?)

2023-08-25 13:09 UTC, hannes commented on _includes/installation.html
> -	<div class="master cli binary macos">
was this div deleted by accident?

2023-08-25 13:25 UTC, szarnyasg commented
> I would also not add curl commands at all, just show the URL so people can click

I removed the commands

2023-08-25 13:55 UTC, merged