Add ODBC guide
duckdb/duckdb-web pull request #1192
Opened 2023-09-20 10:18 UTC by maiadegraaf

This PR introduces a guide on ODBC and how to create an C++ application to connect to our driver.

2023-09-20 11:58 UTC, szarnyasg commented
Funnily enough, my VS Code's Markdown plug-in kept regenerating the table of contents (or rather, what it perceived as the TOC under `Setting up an Application`) upon every save operation. I turned this off using:
https://github.com/yzhang-gh/vscode-markdown/issues/388

2023-09-20 12:10 UTC, szarnyasg commented
I did a pass, it looks good. Three comments:

1. The `<summary>` tag doesn't work and it should be avoided along with `<details>`. Please remove these.
<img width="440" alt="Screenshot 2023-09-20 at 13 54 19" src="https://github.com/duckdb/duckdb-web/assets/1402801/7b36088c-f411-4d4d-9adf-a3b12d2f7216">

2. At the beginning of the `Setting up an Application` section, it would be nice to have a sentence on what we are going to achieve in the sections that follow.

3. We have a lot of ODBC docs at https://duckdb.org/docs/api/odbc/overview. These are of varying quality and likely outdated. Could you take a look at them after this PR? (We can merge this first.)

2023-09-20 12:53 UTC, szarnyasg requested changes
See https://github.com/duckdb/duckdb-web/pull/1192#issuecomment-1727599294

2023-09-20 13:37 UTC, szarnyasg commented on docs/guides/odbc/general.md
> +| `SAVEFILE` | The path to a file to which the connection string should be saved.                                                       |
Got it! I put it back to a comment.

2023-09-20 15:28 UTC, maiadegraaf commented
>     2. At the beginning of the `Setting up an Application` section, it would be nice to have a sentence on what we are going to achieve in the sections that follow.

I did have something like this before, but it got lost somewhere in the move, added it back in now :)

2023-09-21 07:16 UTC, szarnyasg approved these changes
Looks great, thanks. Pushed to nit-fixing commits and will merge this now.

2023-09-21 07:17 UTC, merged