added page for trademark use guidelines
duckdb/duckdb-web pull request #628
Opened 2023-03-13 17:12 UTC by Franz-Kafka

2023-03-15 04:38 UTC, Mause requested changes
Probably needs a section for whether or not these guidelines apply retroactively - there are many projects released in the past that violate these guidelines

2023-03-15 04:38 UTC, Mause commented on trademark_guidelines.md
> +Domain names relating to products or services based on the DuckDBcontaining “duck” are not permitted without written permission from the the DuckDB Foundation. Events, books, and merchandise have the
Looks like some editing mistakes in this line

2023-03-15 04:38 UTC, Mause commented on trademark_guidelines.md
> +We appreciate the community’s help in respecting these guidelines. If you have any questions about the DuckDB trademark guidelines or policy, or if you wish to request permission for any specific use
Email addresses need to be updated

2023-03-31 13:29 UTC, hannes commented
will edit those after merging, thanks

2023-03-31 13:29 UTC, merged

2023-03-31 13:37 UTC, Mause commented on faq.md
> +You can find the gudelines for DUCKDB™ [here](https://duckdb.org/trademark_guidelines).
Also some typos here I didn't notice before