Update 2022-01-06-time-zones.md
duckdb/duckdb-web pull request #665
Opened 2023-03-29 21:23 UTC by davetapley

load instead of require for extension

2023-03-30 03:23 UTC, Mause requested changes

2023-03-31 00:38 UTC, davetapley commented on _posts/2022-01-06-time-zones.md
>  query IIII
Oh neat, is the stuff after `----` the expected output?

Honestly I didn't even notice 😁

2023-04-02 21:02 UTC, Tishj commented on _posts/2022-01-06-time-zones.md
>  query IIII
Yes it is :)

2023-04-12 08:23 UTC, merged

2023-04-12 08:24 UTC, Mause commented
Thanks!