Update
duckdb/duckdb-web pull request #676
Opened 2023-04-09 10:23 UTC by sumitshinde-84

![fotor_2023-4-9_15_50_25](https://user-images.githubusercontent.com/110285294/230767343-eef07d23-916d-4cc1-ad99-81d479c13dd9.png)

1.An array outdatedLinks is created to store the URLs of outdated documentation versions.
2.The window.location.href is checked against the outdatedLinks array using the includes method to determine if the current URL is in the list of outdated links.
3.If the current URL is found in the outdatedLinks array, a new HTML element for the popup is created using document.createElement('div').
4.The content of the popup is set using the innerHTML property, which includes a message about the outdated documentation version and a link to the latest documentation.
5.The styles for the popup, such as background color, padding, text alignment, and z-index, are set using the style property.
6.The popup element is appended to the .headerline element using the appendChild method.
7.An event listener is added to the popup element to close the popup when clicked, using the addEventListener method with a callback function that sets the display property of the popup element to 'none'.

one more thing before testing it locally make sure you have updated array links according to your local server link

2023-04-09 13:45 UTC, Mause requested changes

2023-04-09 13:45 UTC, Mause commented on js/script.js
> -	$('.headlinebar .version').click(function(){
Why remove this code?

2023-04-09 13:45 UTC, Mause commented on js/script.js
> +	  if (outdatedLinks.includes(window.location.href)) {
I'd strongly prefer we implement this using Jekyll Liquid templates instead, then we don't have to hardcode any URLs or versions

2023-04-09 14:44 UTC, sumitshinde-84 commented
ok i have make documentation.yml in ./data and have stored this
 outdatedLinks:
  - 'https://duckdb.org/docs/archive/0.6.1/index'
  - 'https://duckdb.org/docs/archive/0.5.1/index'
  - 'https://duckdb.org/docs/archive/0.4.0/index'
  - 'https://duckdb.org/docs/archive/0.3.4/index'
  - 'https://duckdb.org/docs/archive/0.3.3/index'
  - 'https://duckdb.org/docs/archive/0.3.2/index'
  - 'https://duckdb.org/docs/archive/0.3.1/index'
  - 'https://duckdb.org/docs/archive/0.3.0/index'
  - 'https://duckdb.org/docs/archive/0.2.9/index'
  - 'https://duckdb.org/docs/archive/0.2.8/index'
latestDocumentation: 'https://duckdb.org/docs/archive/0.7.1/index'

and in ./layout/default.html folder i have write 
{% assign outdatedLinks = site.data.documentation.outdatedLinks %}
	{% if outdatedLinks contains page.url %}
		<div id="popup" style="background-color: yellow; padding: 10px; text-align: center; z-index: 9999;">
			This documentation version is outdated. Please refer to the latest <a href="{{ site.data.documentation.latestDocumentation }}">documentation</a>.
		</div>
		<script>
			var outdatedLinks = [
				{% for link in site.data.documentation.outdatedLinks %}
					'{{ link }}',
				{% endfor %}
			];
			if (outdatedLinks.includes(window.location.href)) {
				var popup = document.createElement('div');
				popup.innerHTML = 'This documentation version is outdated. Please refer to the latest <a href="{{ site.data.documentation.latestDocumentation }}">documentation</a>.';
				popup.style.backgroundColor = 'yellow';
				popup.style.padding = '10px';
				popup.style.textAlign = 'center';
				popup.style.zIndex = '9999';
				document.querySelector('.headerline').appendChild(popup);
				popup.addEventListener('click', function() {
					popup.style.display = 'none';
				});
			}
		</script>
	{% endif %}

2023-04-09 14:44 UTC, sumitshinde-84 commented
> ok i have make documentation.yml in ./data and have stored this outdatedLinks:
> 
> * 'https://duckdb.org/docs/archive/0.6.1/index'
> * 'https://duckdb.org/docs/archive/0.5.1/index'
> * 'https://duckdb.org/docs/archive/0.4.0/index'
> * 'https://duckdb.org/docs/archive/0.3.4/index'
> * 'https://duckdb.org/docs/archive/0.3.3/index'
> * 'https://duckdb.org/docs/archive/0.3.2/index'
> * 'https://duckdb.org/docs/archive/0.3.1/index'
> * 'https://duckdb.org/docs/archive/0.3.0/index'
> * 'https://duckdb.org/docs/archive/0.2.9/index'
> * 'https://duckdb.org/docs/archive/0.2.8/index'
>   latestDocumentation: 'https://duckdb.org/docs/archive/0.7.1/index'
> 
> and in ./layout/default.html folder i have write {% assign outdatedLinks = site.data.documentation.outdatedLinks %} {% if outdatedLinks contains page.url %}
> 
> 
> This documentation version is outdated. Please refer to the latest [documentation]({{ site.data.documentation.latestDocumentation }}).
> 
> <script>
> var outdatedLinks = [
> {% for link in site.data.documentation.outdatedLinks %}
> '{{ link }}',
> {% endfor %}
> ];
> if (outdatedLinks.includes(window.location.href)) {
> var popup = document.createElement('div');
> popup.innerHTML = 'This documentation version is outdated. Please refer to the latest [documentation]({{ site.data.documentation.latestDocumentation }}).';
> popup.style.backgroundColor = 'yellow';
> popup.style.padding = '10px';
> popup.style.textAlign = 'center';
> popup.style.zIndex = '9999';
> document.querySelector('.headerline').appendChild(popup);
> popup.addEventListener('click', function() {
> popup.style.display = 'none';
> });
> }
> </script>
> {% endif %}

is it right way of doing this

2023-04-09 14:51 UTC, Mause commented
The current DuckDB release version is already available in https://github.com/duckdb/duckdb-web/blob/b4bc3b65908fdf276c7fbef74c50bc12a65de8c5/_config.yml#L23, so you shouldn't need to maintain another list of versions, and javascript isn't required for this feature at all. Try to stick to pure Jekyll Liquid template scripting

2023-04-09 14:58 UTC, sumitshinde-84 commented
> The current DuckDB release version is already available in
> 
> https://github.com/duckdb/duckdb-web/blob/b4bc3b65908fdf276c7fbef74c50bc12a65de8c5/_config.yml#L23
> 
> , so you shouldn't need to maintain another list of versions, and javascript isn't required for this feature at all. Try to stick to pure Jekyll Liquid template scripting

Ok

2023-04-09 17:14 UTC, sumitshinde-84 commented
{% unless site.currentduckdbversion contains "0.7.1" or page.url contains "/doc/" %}
    {% include documentation-popup.html %}
{% endunless %}   can you help with this what should i add in if condition

2023-04-10 08:29 UTC, sumitshinde-84 commented
If we want to trigger a popup for users who visit old versions of documentation, using the currentduckdbversion may not be suitable as it refers to the current version of DuckDB. Instead, we  may need to use a different approach, such as checking the URL path  to determine if they are viewing old documentation.  

am i right , if wrong please correct me

2023-04-10 14:52 UTC, Alex-Monahan commented
Hello and thanks for your work here! 

@Mause is correct - this is something that should not be done in JavaScript, and you should use the `currentduckdbversion` within your logic. If you search the codebase for `currentduckdbversion`, you can see some examples of how it is used. 

I believe the best location for this would be here: _layouts\docu.html.

Please also use the DuckDB theme colors (`$duckDByellow: #fff100;`, etc.).

2023-04-12 08:21 UTC, Mause requested changes
Still needs work

2023-04-18 05:13 UTC, Mause commented
Closing this for now, feel free to re-open a new one with comments fixed

2023-04-18 05:13 UTC, closed without merging

2023-04-18 05:15 UTC, sumitshinde-84 commented
Ok