Storage
duckdb/duckdb-web pull request #749
Opened 2023-05-12 14:24 UTC by carlopi

Couple of minor fixes, mostly adds some context around storage mismatches (that made sense to me, but is anyone wants to iterate it would be welcome)

2023-05-12 14:31 UTC, Mause requested changes
Just a couple of small types :duck:

2023-05-12 14:31 UTC, Mause commented on _includes/installation.html
> +		git submodule init --update
I don't think we use any submodules in the main repo?

2023-05-12 14:31 UTC, Mause commented on internals/storage.md
> +Opening your database file with older duckdb and usign the SQL statement `"EXPORT DATABASE 'tmp';"` allows to save the whole state of the current database in use inside folder `tmp`.
```suggestion
Opening your database file with the older duckdb and using the SQL statement `"EXPORT DATABASE 'tmp';"` allows you to save the whole state of the current database in use inside folder `tmp`.
```

2023-05-12 14:31 UTC, Mause commented on internals/storage.md
> +Starting then the newer duckdb and executing `"IMPORT DATABASE 'tmp';"` (pointing to the previously populated folder) allow to load the database, that can be then saved to the file you pointed duckdb
```suggestion
Then start the newer duckdb and execute `"IMPORT DATABASE 'tmp';"` (pointing to the previously populated folder) allows you to load the database, which can be then saved to the file you pointed duckdb to.
```

2023-05-12 14:31 UTC, Mause commented on internals/storage.md
> +user@device $ /newer/duckdb mydata.new.db -c "IMPORT DATABASE 'tmp';"
```suggestion
$ /older/version/duckdb mydata.db -c "EXPORT DATABASE 'tmp';"
$ /newer/duckdb mydata.new.db -c "IMPORT DATABASE 'tmp';"
```

2023-05-12 14:31 UTC, Mause commented on internals/storage.md
> +user@device $ hexdump -n 20 -C mydata.db
```suggestion
$ hexdump -n 20 -C mydata.db
```

2023-05-12 14:37 UTC, carlopi commented
@Mause: Thanks for the feedback!

2023-05-14 17:02 UTC, merged

2023-05-14 17:02 UTC, Mause commented
Thanks!