Add documentation for the 'Create Type' statement
duckdb/duckdb-web pull request #859
Opened 2023-07-07 05:16 UTC by Loreith

Disclaimer that I learned all of this from the discord (thanks Elliana and __Alex__!) and trial and error, not from actually reading the source or a grammar file.

Also please feel free to cut down the railroad diagram or examples if you feel like I went a little overboard with it - I just noticed that there wasn't any mention of being able to create structs or unions elsewhere and wanted to be specific about them since the syntax is a little more involved than "just write the type identifier".

2023-07-08 14:30 UTC, Mause requested changes

2023-07-08 14:30 UTC, Mause commented on docs/sql/statements/create_type.md
> +For fully custom operators and things on a custom type, you'll have to go into the
Replace "things"?

2023-07-08 14:30 UTC, Mause commented on docs/sql/statements/create_type.md
> +CREATE TYPE one_thing AS UNION(numer INTEGER, string VARCHAR);
```suggestion
CREATE TYPE one_thing AS UNION(number INTEGER, string VARCHAR);
```
?

2023-07-10 01:16 UTC, Loreith commented on docs/sql/statements/create_type.md
> +CREATE TYPE one_thing AS UNION(numer INTEGER, string VARCHAR);
well done me:p

2023-07-10 02:01 UTC, merged

2023-07-10 02:02 UTC, Mause commented
Thanks!

(Also hi from another Greens person, from Boorloo!)