Move the dev/ pages under docs/. Fixes #938
duckdb/duckdb-web pull request #943
Opened 2023-08-08 09:46 UTC by szarnyasg

I moved the `dev` and the `internal` directories under `docs` and adjusted the JSON menus accordingly.

As explained in #938, this helps versioning these pages.

However, note that merging this PR will break existing URLs such as https://duckdb.org/internals/storage.

\Maybe we should add some redirects to ensure that these still work?

Let me know what you think.

2023-08-08 11:21 UTC, carlopi commented
internals/storage is referred from any duckdb version in a somehow frequently seen error message, so I would aim for that link to be always be valid (redirect / copy of content / keeping that page there and moving the rest). It's also special in the sense that's a page that has to be valid cross version.

The rest is fine either way.

2023-08-08 11:25 UTC, szarnyasg commented
Thanks, very good point. I pushed a commit that fixes this.

2023-08-08 11:32 UTC, szarnyasg commented
@Mause @Alex-Monahan pls let me know what you think.

2023-08-08 14:05 UTC, Mause commented
Can you explain why you want to version these pages? As far as I can see, unless someone wants to work on an old version, they won't need the old dev docs

2023-08-08 14:07 UTC, szarnyasg commented
After v1.0, I expect quite a few people to anchor down on a given version, so it will be beneficial if these are also versioned, archived. They should also be part of the PDF.

2023-08-08 15:00 UTC, Mause commented on docs/dev/internals/storage.md
> +redirect_from:
This file shouldn't be moved - there should only be one copy that contains the information for all the versions at once

2023-08-08 15:02 UTC, szarnyasg commented
I think it cannot hurt for 0.9 either.

And a major benefit or merging this now would be that it would allow for a uniform handling of {docs, guides, dev, internal} pages for the single PDF document, which IMHO should also contain the dev and internal pages.

2023-08-10 13:33 UTC, Mause requested changes
Storage should be moved outside of versioning

2023-08-10 13:46 UTC, szarnyasg commented
At the moment, it is a bit unclear to me where the developer docs should be. It could also be a wiki that's separate from the main documentation.
In any case, my priority now is to get the user documentation plus guides out in a single-PDF build, so I'll close this now and revisit it later.

2023-08-10 13:46 UTC, closed without merging