Readjust headers of document files
duckdb/duckdb-web pull request #976
Opened 2023-08-12 08:15 UTC by szarnyasg

2023-08-13 13:42 UTC, szarnyasg commented
I did a quick test with the following Markdown file:

```md
# h1

## h2

Some text in the chapter.

### h3

Some text in the section.

#### h4

Some text in the subsection.

##### h5

Some text in the subsubsection.

###### h6

Some text in the paragraph.

####### h7

Some text in the subparagraph.
```

When run through...

```bash
pandoc my.md --to=pdf --top-level-division=part --template=eisvogel2.tex --data-dir=. --output=out.pdf --pdf-engine=xelatex --variable book=true --variable numbersections=true
```

it produces:

<img width="531" alt="Screenshot 2023-08-13 at 15 35 18" src="https://github.com/duckdb/duckdb-web/assets/1402801/b482aec1-5aa6-4483-9e8b-4ce1127bf978">

So while pandoc allows level 7 headers. (Meanwhile, `h7` is not a valid HTML element.) It's not that great but it gives us 3 headers level for each page to use (where they will be `h2`, `h3`, and `h4` (i.e. `##`, `###`, and `####` in Markdown). 

The PDF will be structured (with examples) as

- `#` Part: Docs
  - `##` Chapter: SQL
    - `###` Section: Statements
      - `####` Subsection: CREATE TABLE
        - ...and here comes the content from `create_table.md`

It's important (for me) to keep in mind that ~99% of the users will read the HTML, so that has to look good, the PDF is less important.

2023-08-13 15:43 UTC, szarnyasg commented
Okay, this looks good now! I generated a PDF and its ToC also looked good (there was no random "jitter" when e.g. a h2 header is followed by an h4 immediately followed by an h3).

@Mause please let me know if this is good to merge.

2023-08-14 16:02 UTC, Mause requested changes

2023-08-14 16:02 UTC, Mause commented on docs/data/csv/overview.md
> +## The DuckDB CSV reader
```suggestion
## CSV reader
```

2023-08-14 16:06 UTC, szarnyasg commented on docs/api/cpp.md
> +TODO
Yes, this is an empty section. But the TODO won't be there for long, I want to deal with all visible TODOs in #987.

2023-08-14 16:13 UTC, merged