Extend build guide
duckdb/duckdb-web pull request #985
Opened 2023-08-14 14:39 UTC by szarnyasg

2023-09-06 16:34 UTC, szarnyasg commented
Windows is tough. I added a pointer to the CI instructions but would not spend more cycles than this on providing detailed instructions – they can vary a lot based on whether someone is using WSL, MinGW, Cygwin, CLion, vanilla VS, etc.

2023-09-07 00:54 UTC, Mause requested changes

2023-09-07 00:54 UTC, Mause commented on dev/building.md
> +##### `format-fix` | `format-changes` | `format-master`
```suggestion
##### `format-fix` | `format-changes` | `format-main`
```

2023-09-07 00:54 UTC, Mause commented on dev/building.md
> +More information about this can be found [here](https://github.com/duckdb/duckdb/blob/master/benchmark/README.md).
```suggestion
More information about this can be found [here](https://github.com/duckdb/duckdb/blob/main/benchmark/README.md).
```

2023-09-07 00:54 UTC, Mause commented on dev/building.md
> +```
```suggestion
```bash
```

2023-09-07 06:45 UTC, szarnyasg commented
Thanks for catching these!

2023-09-07 07:02 UTC, Mause approved these changes

2023-09-07 07:11 UTC, merged